## Version: 11/25/2012 10:38:29 PM
## Description: Plot ancestral state reconstructions on nodes
## Requirements: R package "phyloch", v. 1.5-1
## Input: bip.txt, chars.txt. Files generated by running Perl script SplitStatFile.pl on SIMMAP (v.1.5) output.
## By: Johan.Nylander@bils.se

require("phyloch")
treefile <- "croc.tre"
bipartitionfile <- "bip.txt"
charsfile <- "chars.txt"
col0 <- "white"
col1 <- "red"
col2 <- "blue"
col3 <- "green"
col4 <- "purple"
col5 <- "orange"
col6 <- "gray"
pie.col <- c(col0, col1, col2, col3, col4, col5, col6)
pie.cex <- 0.5
tipcex <- 0.5
nodenumbercex <- 0.2
pdfwidth <- 10
pdfheight <- 12
labeloffset <- 0.01

tre <- ladderize(read.nexus(treefile), right = FALSE)
taxa <- tre$tip.label
tre <- fixNodes(tre)
biptable <- read.table(bipartitionfile, header = FALSE, row.names = 1, colClasses = "character")
bips <- biptable$V2
chars <- read.table(charsfile, header = TRUE,  sep = "\t", check.names = FALSE)
"RemoveAllMissing" <- function(x) {
    rem <- NULL
    for (col.nr in 1:dim(x)[2]) {
        if (all(x[,col.nr] == '-')) {
            rem <- c(rem, col.nr)
        }
    }
    if (is.null(rem)) {
        return(x)
    } else {
        x <- x[, -rem]
        return(x)
    }
}
chars <- RemoveAllMissing(chars)
thechars <- unique(chars$Site)
for (c in 1:length(thechars)) {
    cat("\n\nDoing character:", c, "\n")
    outtreepdf <- paste(treefile, ".pdf", sep = "")
    outpdf <- paste("Char.", thechars[c], ".pdf", sep = "")
    outsvg <- paste("Char.", thechars[c], ".svg", sep = "")
    outtxt <- paste("Char.", thechars[c], ".txt", sep = "")
    charc <- chars[chars$Site == thechars[c], ]
    charc <- RemoveAllMissing(charc)
    pdf(outtreepdf, width = pdfwidth, height = pdfheight)
    plot(tre, cex = tipcex, label.offset = labeloffset)
    nodelabels(cex = nodenumbercex)
    dev.off()
    pdf(file = outpdf, width = pdfwidth, height = pdfheight)
#    svg(file = outsvg, width = pdfwidth, height = pdfheight)
    plot(tre, cex = tipcex, label.offset = labeloffset, no.margin = FALSE)
    cat("SIMMAP-node", "Phylo-node", "Piedata", file = outtxt)
    cat("\n", file = outtxt, append = TRUE)
    for (i in 1:length(bips)) {
        t <- taxa[as.logical(as.numeric(unlist(strsplit(bips[i], ""))))]
        if ( is.monophyletic(tre, t) ) {
            j <- noi(tre, t)
            piedatam <- as.matrix(subset(charc, charc$Clade == i, select = -c(Site, Clade, N)))
            piedata <- as.numeric(piedatam)
            cat("SIMMAP-node:", i, ", Phylo-node:", j, ", piedata:", piedata, "\n")
            cat(i, j, piedata, file = outtxt, append = TRUE)
            cat("\n", file = outtxt, append = TRUE)
            nodelabels(node = j, pie = rbind(piedata), piecol = pie.col, cex = pie.cex)
        }
    }
    legend(title = "Char. state", legend = colnames(piedatam), x = "topleft", col = "black",
           pt.bg = pie.col, pt.cex = 1.5, pt.lwd = 1, bg = "white", pch = 21, bty = "n", cex = 0.8)
    dev.off()
}

